### PR TITLE
fix bit calculation

### PR DESCRIPTION
**Pull request by popop098**
I read #488 issue and I fixed it
maybe works fine🥴

### CODE REVIEW

**Comment by SaidBySolo** [comment]
Related https://github.com/koreanbots/core/pull/489

**Review by SaidBySolo — COMMENTED** [review]
This seems to have to be done using bitwise operators. 

I think this is the wrong approach

We need a review from the core developer first.

**Review by wonderlandpark — CHANGES_REQUESTED** [review]
Bitwise operation needed during handling permission

Ref: https://discord.com/developers/docs/topics/permissions

**Comment by wonderlandpark** [comment]
This looks like a extension of #489 (or dupe)

**Pull request closed without merging**
